### ISSUE TITLE
Cannot run ses-048 and ses-041 through fMRIPrep

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#396]
@oesteban It generates the following error. Did you do something different in the last session (at least not according to sessions note)?

> Traceback (most recent call last):
>   File "/opt/conda/envs/fmriprep/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
>     self.run()
>   File "/opt/conda/envs/fmriprep/lib/python3.10/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/cli/workflow.py", line 115, in build_workflow
>     retval["workflow"] = init_fmriprep_wf()
>   File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/workflows/base.py", line 93, in init_fmriprep_wf
>     single_subject_wf = init_single_subject_wf(subject_id)
>   File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/workflows/base.py", line 571, in init_single_subject_wf
>     raise NotImplementedError("Sophisticated PEPOLAR schemes are unsupported.")
> NotImplementedError: Sophisticated PEPOLAR schemes are unsupported.

Does it mean this session needs to be reacquired?

**Comment by oesteban** [comment]
That's weird, we haven't configured the fieldmaps to be workable by fMRIPrep. Looks like heudiconv inserted some "IntendedFor" fields in some fieldmap within this session only.

**Comment by oesteban** [comment]
I'm working on consolidating the JSON files AND will soon get to assigning `B0FieldIdentifier`s, which should address this.

**Comment by celprov** [comment]
@oesteban I'm still running into this PEPOLAR issue for those two sessions (at 6pm). Do you think it did not finish rsyncing yet or the problem is not solved by the latest changes you made?

cc @acionca

**Comment by celprov** [comment]
Even the latest fMRIPrep-23.2.0a2 did not successfully run on those two sessions
