### ISSUE TITLE
Build preview is broken in CircleCI

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#473]
The build preview fails in CircleCI
```
#!/bin/bash -eo pipefail
python -m mkdocs build --site-dir _SOPs_preview
```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.10/site-packages/mkdocs/__main__.py", line 366, in <module>
>     cli()
>   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/mkdocs/__main__.py", line 281, in build_command
>     cfg = config.load_config(**kwargs)
>   File "/usr/local/lib/python3.10/site-packages/mkdocs/config/base.py", line 374, in load_config
>     errors, warnings = cfg.validate()
>   File "/usr/local/lib/python3.10/site-packages/mkdocs/config/base.py", line 231, in validate
>     run_failed, run_warnings = self._validate()
>   File "/usr/local/lib/python3.10/site-packages/mkdocs/config/base.py", line 188, in _validate
>     self[key] = config_option.validate(value)
>   File "/usr/local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 186, in validate
>     return self.run_validation(value)
>   File "/usr/local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 1075, in run_validation
>     self.load_plugin_with_namespace(name, cfg)
>   File "/usr/local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 1113, in load_plugin_with_namespace
>     return (name, self.load_plugin(name, config))
>   File "/usr/local/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 1131, in load_plugin
>     plugin_cls = self.installed_plugins[name].load()
>   File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
>     module = import_module(match.group('module'))
>   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/usr/local/lib/python3.10/site-packages/mkdocs_jupyter/plugin.py", line 9, in <module>
>     from mkdocs.tests.base import get_markdown_toc
> ModuleNotFoundError: No module named 'mkdocs.tests'
> 
> Exited with code exit status 1

**Comment by celprov** [comment]
Solved by #472
