### ISSUE TITLE
Installation of mriqc-learn github repo fails

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#485]
There is a bug in installing the requirements of the hcph-sops using ` pip install -r requirements.txt `

```
Collecting git+https://github.com/celprov/mriqc-learn.git@enh/xgboost_model (from -r requirements.txt (line 14))
  Cloning https://github.com/celprov/mriqc-learn.git (to revision enh/xgboost_model) to /private/var/folders/8k/n35g787n5nq7x7mftl9bxlb80000gn/T/pip-req-build-vbtlqwuc
  Running command git clone --filter=blob:none --quiet https://github.com/celprov/mriqc-learn.git /private/var/folders/8k/n35g787n5nq7x7mftl9bxlb80000gn/T/pip-req-build-vbtlqwuc
  Running command git checkout -b enh/xgboost_model --track origin/enh/xgboost_model
  Switched to a new branch 'enh/xgboost_model'
  branch 'enh/xgboost_model' set up to track 'origin/enh/xgboost_model'.
  Resolved https://github.com/celprov/mriqc-learn.git to commit 4cea98eff04c4bd6027e2271f3320a7069162ef5
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/Users/cprovins/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/cprovins/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/cprovins/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/Users/cprovins/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/cprovins/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/8k/n35g787n5nq7x7mftl9bxlb80000gn/T/pip-build-env-1_mqwtp1/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/private/var/folders/8k/n35g787n5nq7x7mftl9bxlb80000gn/T/pip-build-env-1_mqwtp1/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/private/var/folders/8k/n35g787n5nq7x7mftl9bxlb80000gn/T/pip-build-env-1_mqwtp1/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2158, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by oesteban** [comment]
Please move to nipreps/mriqc-learn

**Comment by oesteban** [comment]
I have updated mriqc-learn -- you'll need to update your branch.
