### ISSUE TITLE
Installation of matplotlib==3.3 fails

### ISSUE THREAD

**Issue by celprov** [TheAxonLab/hcph-sops#486]
There is a bug in installing the requirements of hcph-sops using `pip install -r requirements.txt`

```Collecting git+https://github.com/dimrozakis/mkpdfs-mkdocs-plugin.git@master (from -r requirements.txt (line 8))
  Cloning https://github.com/dimrozakis/mkpdfs-mkdocs-plugin.git (to revision master) to /private/var/folders/8k/n35g787n5nq7x7mftl9bxlb80000gn/T/pip-req-build-uiobo9j9
  Running command git clone --filter=blob:none --quiet https://github.com/dimrozakis/mkpdfs-mkdocs-plugin.git /private/var/folders/8k/n35g787n5nq7x7mftl9bxlb80000gn/T/pip-req-build-uiobo9j9
  Resolved https://github.com/dimrozakis/mkpdfs-mkdocs-plugin.git to commit d765be71e7a854f53f481b43f9d5a5527771179d
  Preparing metadata (setup.py) ... done
Requirement already satisfied: codespell in /Users/cprovins/miniconda3/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (2.3.0)
Collecting markdown-include (from -r requirements.txt (line 2))
  Downloading markdown_include-0.8.1-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: mkdocs in /Users/cprovins/miniconda3/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (1.6.0)
Collecting mkdocs-jupyter~=0.24.7 (from -r requirements.txt (line 4))
  Downloading mkdocs_jupyter-0.24.8-py3-none-any.whl.metadata (9.4 kB)
Collecting mkdocs-macros-plugin (from -r requirements.txt (line 5))
  Downloading mkdocs_macros_plugin-1.0.5-py3-none-any.whl.metadata (7.4 kB)
Collecting mkdocs-material>=9.4 (from -r requirements.txt (line 6))
  Downloading mkdocs_material-9.5.31-py3-none-any.whl.metadata (17 kB)
Collecting git-changelog (from -r requirements.txt (line 7))
  Downloading git_changelog-2.5.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: pygments in /Users/cprovins/miniconda3/lib/python3.12/site-packages (from -r requirements.txt (line 9)) (2.18.0)
Collecting weasyprint<53 (from -r requirements.txt (line 10))
  Downloading WeasyPrint-52.5-py3-none-any.whl.metadata (3.5 kB)
Collecting matplotlib==3.3 (from -r requirements.txt (line 11))
  Downloading matplotlib-3.3.0.tar.gz (38.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.8/38.8 MB 65.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/8k/n35g787n5nq7x7mftl9bxlb80000gn/T/pip-install-7_8knn3m/matplotlib_502afc22f8e44a83a24a9d0f819e023e/setup.py", line 52, in <module>
          __version__ = versioneer.get_version()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8k/n35g787n5nq7x7mftl9bxlb80000gn/T/pip-install-7_8knn3m/matplotlib_502afc22f8e44a83a24a9d0f819e023e/versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/8k/n35g787n5nq7x7mftl9bxlb80000gn/T/pip-install-7_8knn3m/matplotlib_502afc22f8e44a83a24a9d0f819e023e/versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/8k/n35g787n5nq7x7mftl9bxlb80000gn/T/pip-install-7_8knn3m/matplotlib_502afc22f8e44a83a24a9d0f819e023e/versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

**Comment by oesteban** [comment]
Addressed: the offending dependencies are gone. #562 dropped the unmaintained `mkpdfs-mkdocs-plugin` (@master git fork) and its `WeasyPrint<53` dependency, and #564 pinned the scientific stack — `matplotlib==3.10.6` (no longer `3.3`). `pip install -r requirements.txt` resolves cleanly now. Closing.
